from __future__ import annotations

from app.workshops.contracts import Workshop, WorkshopAction

WORKSHOP = Workshop(
    area='memory',
    purpose='Normalna praca ze wspomnieniami: szukanie, odczyt, zapis i linki.',
    min_profile='clean_operator',
    risk='low',
    recommended_first_action='find',
    actions=(
        WorkshopAction(
            action='find',
            tool_name='find_memories',
            purpose='Szukaj memories po tekĹ›cie, projekcie i tagach.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'text_query': 'str', 'project_key': 'str|null', 'project_key_mode': 'str', 'limit': 'int', 'include_history': 'bool', 'debug': 'bool'},
        ),
        WorkshopAction(
            action='gravity_preview',
            tool_name='get_agent_gravity_preview',
            purpose='Read-only source-bound project resurfacing preview; never creates truth or links.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'query': 'str', 'project_key': 'str', 'limit': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='gravity_shadow',
            tool_name='get_agent_gravity_shadow',
            purpose='Read-only comparison of canonical memory ids against a Gravity-augmented shadow view.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'query': 'str', 'project_key': 'str', 'baseline_memory_ids_json': 'str', 'max_injections': 'int'},
        ),
        WorkshopAction(
            action='hybrid_search',
            tool_name='hybrid_search_memories',
            purpose='Deterministic Retrieval v2: lexical + semantic + recency with project-bound candidates.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'query': 'str', 'project_key': 'str|null', 'limit': 'int', 'include_gravity': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='context',
            tool_name='build_agent_context',
            purpose='Compose bounded source-linked context for one project and intent.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'intent': 'str', 'project_key': 'str', 'token_budget': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='steward_before_action',
            tool_name='preview_memory_steward_before_action',
            purpose='Read-only Memory Steward before-action context preview.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'intent': 'str', 'project_key': 'str', 'token_budget': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='steward_after_action',
            tool_name='preview_memory_steward_after_action',
            purpose='Build a source-evidenced after-action capture proposal without persistence.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'action_summary': 'str', 'outcome_summary': 'str', 'durable_delta': 'str', 'project_key': 'str', 'conversation_key': 'str|null', 'source_context': 'str|null', 'source_event_ref': 'str|null', 'source_memory_ids_json': 'str|null'},
        ),
        WorkshopAction(
            action='steward_session_close',
            tool_name='preview_memory_steward_session_close',
            purpose='Build a source-evidenced session-close checkpoint proposal without persistence.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'completed_summary': 'str', 'open_items_summary': 'str', 'next_step': 'str', 'project_key': 'str', 'conversation_key': 'str|null', 'source_context': 'str|null', 'source_event_ref': 'str|null', 'source_memory_ids_json': 'str|null'},
        ),
        WorkshopAction(
            action='steward_nightly',
            tool_name='preview_memory_steward_nightly',
            purpose='Aggregate Sandman, retention and review queues into one read-only nightly plan.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'candidate_limit': 'int', 'proposal_budget': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='onboarding_status',
            tool_name='get_mapi_onboarding',
            purpose='Read first-run Polaris onboarding state and the next single question to ask.',
            min_profile='clean_operator', risk='low', risk_class='R0',
            payload_schema={},
        ),
        WorkshopAction(
            action='onboarding_advance',
            tool_name='advance_mapi_onboarding',
            purpose='Save one onboarding draft answer; final summary confirmation commits the reviewed profile.',
            min_profile='clean_operator', risk='medium', risk_class='R2',
            payload_schema={'step': 'str', 'value': 'str|null', 'skip': 'bool'},
            payload_constraints={
                'step': {'enum': ['agent_name', 'user_name', 'work_context', 'autonomy_level', 'memory_policy', 'memory_exclusions', 'first_project', 'summary_confirmation']},
            },
        ),
        WorkshopAction(
            action='onboarding_revise',
            tool_name='revise_mapi_onboarding',
            purpose='Revise one draft onboarding answer while the final summary is awaiting confirmation.',
            min_profile='clean_operator', risk='medium', risk_class='R2',
            payload_schema={'step': 'str', 'value': 'str|null', 'skip': 'bool'},
            payload_constraints={
                'step': {'enum': ['agent_name', 'user_name', 'work_context', 'autonomy_level', 'memory_policy', 'memory_exclusions', 'first_project']},
            },
        ),
        WorkshopAction(
            action='onboarding_skip',
            tool_name='skip_mapi_onboarding',
            purpose='Skip the remaining onboarding without disabling normal Polaris memory work.',
            min_profile='clean_operator', risk='medium', risk_class='R2',
            payload_schema={'reason': 'str|null'},
        ),
        WorkshopAction(
            action='self_healing_status',
            tool_name='get_memory_self_healing_status',
            purpose='Read local self-healing queue health without exposing memory content.',
            min_profile='clean_operator', risk='low', risk_class='R0',
            payload_schema={},
        ),
        WorkshopAction(
            action='self_healing_issue',
            tool_name='get_memory_self_healing_issue',
            purpose='Read one unresolved self-healing issue and its bounded memory evidence for model analysis.',
            min_profile='clean_operator', risk='low', risk_class='R0',
            payload_schema={'issue_id': 'int', 'include_content': 'bool'},
        ),
        WorkshopAction(
            action='self_healing_propose',
            tool_name='propose_memory_self_healing_resolution',
            purpose='Let the connected assistant model propose a canonical resolution for an ambiguous memory branch; does not mutate memories.',
            min_profile='clean_operator', risk='medium', risk_class='R1',
            payload_schema={'issue_id': 'int', 'selected_memory_id': 'int', 'confidence': 'float', 'rationale': 'str'},
        ),
        WorkshopAction(
            action='self_healing_confirm',
            tool_name='confirm_memory_self_healing_resolution',
            purpose='Apply or reject a model-proposed ambiguous memory repair after explicit user consent; approved apply creates a verified backup first.',
            min_profile='clean_operator', risk='medium', risk_class='R2',
            payload_schema={'issue_id': 'int', 'approve': 'bool'},
        ),
        WorkshopAction(
            action='self_snapshot',
            tool_name='get_agent_self_snapshot',
            purpose='Evidence-first read-only self snapshot for one configured agent subject.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'limit': 'int', 'include_content': 'bool'},
        ),
        WorkshopAction(
            action='commitment_ledger',
            tool_name='get_agent_commitment_ledger',
            purpose='Read-only explicit commitment and guardrail ledger for one agent subject.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'limit': 'int', 'include_content': 'bool'},
        ),
        WorkshopAction(
            action='autobiographical_timeline',
            tool_name='get_agent_autobiographical_timeline',
            purpose='Bounded chronological self-evidence timeline without semantic identity inference.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'limit': 'int', 'include_content': 'bool'},
        ),
        WorkshopAction(
            action='self_capsule',
            tool_name='get_agent_self_capsule',
            purpose='Compact source-linked agent self capsule for bootstrap and context composition.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'limit': 'int', 'include_content': 'bool'},
        ),
        WorkshopAction(
            action='self_delta',
            tool_name='get_agent_self_delta',
            purpose='Read-only deterministic comparison of a prior Agent Self Snapshot to another or current snapshot.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'from_snapshot_json': 'str', 'to_snapshot_json': 'str|null', 'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='self_narrative',
            tool_name='get_agent_self_narrative',
            purpose='Controlled source-bound self narrative; optional Gemini may select known claim IDs only.',
            min_profile='reader', risk='low', risk_class='R0',
            payload_schema={'provider': 'str', 'subject_key': 'str|null', 'display_name': 'str|null', 'project_key': 'str|null', 'include_global': 'bool', 'include_debug': 'bool'},
            payload_constraints={'provider': {'enum': ['deterministic', 'gemini']}},
        ),
        WorkshopAction(
            action='list_page',
            tool_name='list_memories_page',
            purpose='Stable keyset-paginated memory inventory with field projection and compact responses.',
            min_profile='clean_operator',
            risk='low',
            risk_class='R0',
            payload_schema={
                'page_size': 'int', 'cursor': 'str|null', 'project_key': 'str|null', 'project_key_mode': 'str',
                'scope_code': 'str|null', 'memory_type': 'str|null', 'state_code': 'str|null', 'truth_kind': 'str|null',
                'tag': 'str|null', 'include_archived': 'bool', 'compact': 'bool', 'fields': 'array|null',
            },
            payload_constraints={'project_key_mode': {'enum': ['exact', 'aliases']}},
        ),
        WorkshopAction(
            action='recent',
            tool_name='recent_memories',
            purpose='Pobierz ostatnie memories chronologicznie.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null',
 'project_key_mode': 'str',
 'limit': 'int',
 'memory_type': 'str|null',
 'layer_code': 'str|null',
 'area_code': 'str|null',
 'state_code': 'str|null',
 'scope_code': 'str|null',
 'include_links': 'bool',
 'include_history': 'bool',
 'debug': 'bool'},
        ),
        WorkshopAction(
            action='restore_ritual',
            tool_name='get_memory_restore_ritual',
            purpose='Zbuduj rytual przywrocenia pamieci: remembered/uncertain/next.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'full': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='compare_modes',
            tool_name='compare_memory_modes',
            purpose='Porownaj klasyczny retrieval v1 z rytualem/przebitka v2 dla tego samego query.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'query': 'str', 'project_key': 'str|null', 'limit': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='forgetting_review',
            tool_name='get_memory_forgetting_review',
            purpose='Operator review dla stale/proposed/archive/superseded hygiene.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'limit': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='health_report',
            tool_name='get_memory_health_report',
            purpose='Read-only raport zdrowia Memory v2: summary, review buckets oraz apply/rollback snapshot integrity.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null',
 'limit': 'int',
 'include_debug': 'bool',
 'include_consolidation_snapshot_integrity': 'bool',
 'snapshot_integrity_sample_limit': 'int'},
        ),
        WorkshopAction(
            action='relation_contracts',
            tool_name='get_memory_relation_contracts',
            purpose='Read canonical evidence-bound contracts for supports/contradicts/supersedes/refines/derived_from/about_project.',
            min_profile='reader',
            risk='low',
            risk_class='R0',
            payload_schema={'relation': 'str|null'},
            payload_constraints={'relation': {'enum': ['supports', 'contradicts', 'supersedes', 'refines', 'derived_from', 'about_project']}},
        ),
        WorkshopAction(
            action='relation_preview',
            tool_name='preview_memory_relation',
            purpose='Read-only evidence preview for one canonical memory relation without applying it.',
            min_profile='reader',
            risk='low',
            risk_class='R0',
            payload_schema={
                'relation': 'str',
                'from_memory_id': 'int|null',
                'to_memory_id': 'int|null',
                'project_key': 'str|null',
                'evidence_kind': 'str|null',
                'evidence_ref': 'str|null',
                'reason': 'str|null',
                'include_debug': 'bool',
            },
            payload_constraints={
                'relation': {'enum': ['supports', 'contradicts', 'supersedes', 'refines', 'derived_from', 'about_project']},
                'evidence_kind': {'enum': ['same_source_event_ref', 'explicit_support_attestation', 'explicit_source_memory_reference']},
            },
        ),
        WorkshopAction(
            action='relation_apply',
            tool_name='apply_memory_relation',
            purpose='Guarded evidence-bound apply for supports or derived_from; requires fresh preview hash and explicit confirmation.',
            min_profile='maintainer',
            risk='medium',
            risk_class='R2',
            payload_schema={
                'relation': 'str',
                'from_memory_id': 'int',
                'to_memory_id': 'int',
                'evidence_kind': 'str',
                'evidence_ref': 'str',
                'reason': 'str',
                'expected_preview_hash': 'str',
                'applied_by': 'str',
                'confirm_evidence_bound_relation': 'bool',
                'project_key': 'str|null',
                'include_debug': 'bool',
            },
            payload_constraints={
                'relation': {'enum': ['supports', 'derived_from']},
                'evidence_kind': {'enum': ['same_source_event_ref', 'explicit_support_attestation', 'explicit_source_memory_reference']},
            },
        ),
        WorkshopAction(
            action='relation_rollback_preview',
            tool_name='preview_memory_relation_rollback',
            purpose='Read-only rollback preview for an evidence-bound supports/derived_from link.',
            min_profile='reader',
            risk='low',
            risk_class='R0',
            payload_schema={'link_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='relation_rollback',
            tool_name='rollback_memory_relation',
            purpose='Rollback an evidence-bound supports/derived_from link by archiving only its materialized edge; audit events remain append-only.',
            min_profile='maintainer',
            risk='medium',
            risk_class='R2',
            payload_schema={
                'link_id': 'int',
                'expected_rollback_preview_hash': 'str',
                'rolled_back_by': 'str',
                'notes': 'str|null',
                'include_debug': 'bool',
            },
        ),
        WorkshopAction(
            action='current_state',
            tool_name='get_memory_current_state',
            purpose='Resolve one memory lineage to the canonical current head and preserved history.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'memory_id': 'int', 'include_history': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='current_state_inventory',
            tool_name='get_memory_current_state_inventory',
            purpose='Read-only inventory of half-supersession, ambiguous heads and lineage issues.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'limit': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_integrity',
            tool_name='get_memory_lifecycle_integrity_report',
            purpose='Read-only raport integralnosci lifecycle i lineage dla Memory v3 contracts.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'memory_id': 'int|null',
 'project_key': 'str|null',
 'scope_code': 'str|null',
 'include_archived': 'bool',
 'sample_limit': 'int',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_inventory',
            tool_name='get_memory_lifecycle_remediation_inventory',
            purpose='Read-only inventory allowlisted legacy lifecycle remediation plan.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'plan_version': 'str', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_preview',
            tool_name='preview_memory_lifecycle_remediation',
            purpose='Read-only guarded preview allowlisted legacy lifecycle remediation plan.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'plan_version': 'str', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_inventory',
            tool_name='get_memory_pointer_lifecycle_remediation_inventory',
            purpose='Read-only global inventory of pointer-only lifecycle lineages.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'plan_version': 'str', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_preview',
            tool_name='preview_memory_pointer_lifecycle_remediation',
            purpose='Read-only guarded preview of pointer-only lifecycle canonicalization.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'plan_version': 'str', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_execution_preview',
            tool_name='preview_memory_pointer_lifecycle_remediation_execution',
            purpose='Build or revalidate a frozen read-only pointer lifecycle execution manifest.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'plan_version': 'str',
 'execution_policy_version': 'str',
 'execution_scope': 'str',
 'approved_execution_manifest_json': 'str|null',
 'expected_execution_manifest_fingerprint': 'str|null',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_execution_apply',
            tool_name='apply_memory_pointer_lifecycle_remediation_execution',
            purpose='Execute an explicitly approved frozen pointer lifecycle manifest.',
            min_profile='clean_operator',
            risk='high',
            payload_schema={'plan_version': 'str',
 'execution_policy_version': 'str',
 'approved_execution_manifest_json': 'str',
 'expected_execution_manifest_fingerprint': 'str',
 'expected_execution_preview_hash': 'str',
 'approved_protected_component_ids_json': 'str',
 'applied_by': 'str',
 'reason': 'str',
 'confirm_data_repair': 'bool',
 'confirm_protected': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_execution_run',
            tool_name='get_memory_pointer_lifecycle_remediation_execution_run',
            purpose='Inspect a pointer lifecycle execution run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_execution_rollback_preview',
            tool_name='preview_memory_pointer_lifecycle_remediation_execution_rollback',
            purpose='Preview exact rollback of a pointer lifecycle execution run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='pointer_lifecycle_remediation_execution_rollback',
            tool_name='rollback_memory_pointer_lifecycle_remediation_execution',
            purpose='Execute exact guarded rollback of a pointer lifecycle execution run.',
            min_profile='clean_operator',
            risk='high',
            payload_schema={'run_id': 'int', 'expected_rollback_preview_hash': 'str', 'rolled_back_by': 'str', 'notes': 'str|null'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_apply',
            tool_name='apply_memory_lifecycle_remediation',
            purpose='Execute guarded allowlisted legacy lifecycle remediation after explicit confirmation.',
            min_profile='clean_operator',
            risk='high',
            payload_schema={'plan_version': 'str',
 'expected_preview_hash': 'str',
 'expected_candidate_set_fingerprint': 'str',
 'applied_by': 'str',
 'reason': 'str',
 'confirm_data_repair': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_run',
            tool_name='get_memory_lifecycle_remediation_run',
            purpose='Inspect one legacy lifecycle remediation run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_rollback_preview',
            tool_name='preview_memory_lifecycle_remediation_rollback',
            purpose='Read-only preview of snapshot-based legacy remediation rollback.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='lifecycle_remediation_rollback',
            tool_name='rollback_memory_lifecycle_remediation',
            purpose='Execute guarded snapshot-based legacy remediation rollback.',
            min_profile='clean_operator',
            risk='high',
            payload_schema={'run_id': 'int', 'expected_rollback_preview_hash': 'str', 'rolled_back_by': 'str', 'notes': 'str|null'},
        ),
        WorkshopAction(
            action='consolidation_queue',
            tool_name='list_memory_consolidation_proposals',
            purpose='Lista proposal queue dla konsolidacji memory v2.1.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'status': 'str|null',
 'proposal_type': 'str|null',
 'project_key': 'str|null',
 'limit': 'int',
 'include_rejected': 'bool'},
        ),
        WorkshopAction(
            action='consolidation_get',
            tool_name='get_memory_consolidation_proposal',
            purpose='Szczegoly jednej propozycji konsolidacji.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'proposal_id': 'str'},
        ),
        WorkshopAction(
            action='consolidation_approve',
            tool_name='approve_memory_consolidation_proposal',
            purpose='Zatwierdz proposal review-only, bez mutacji source memories.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'proposal_id': 'str', 'review_note': 'str|null', 'reviewed_by': 'str|null'},
        ),
        WorkshopAction(
            action='consolidation_reject',
            tool_name='reject_memory_consolidation_proposal',
            purpose='Odrzuc proposal review-only z wymaganym powodem.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'proposal_id': 'str', 'reason': 'str', 'reviewed_by': 'str|null'},
        ),
        WorkshopAction(
            action='consolidation_apply_preview',
            tool_name='preview_apply_memory_consolidation_proposal',
            purpose='Preview rollback-safe apply planu dla approved consolidation proposal; zwraca wymagany preview_hash do apply.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'proposal_id': 'str'},
        ),
        WorkshopAction(
            action='consolidation_apply',
            tool_name='apply_approved_memory_consolidation_proposal',
            purpose='Wykonaj rollback-safe apply dla approved merge_duplicates proposal; expected_preview_hash z preview jest wymagany.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'proposal_id': 'str', 'notes': 'str|null', 'applied_by': 'str|null', 'expected_preview_hash': 'str'},
        ),
        WorkshopAction(
            action='consolidation_apply_runs',
            tool_name='list_memory_consolidation_apply_runs',
            purpose='Lista read-only audytow wykonanych consolidation_apply_run.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null',
 'proposal_id': 'str|null',
 'status': 'str|null',
 'created_after': 'str|null',
 'created_before': 'str|null',
 'limit': 'int'},
        ),
        WorkshopAction(
            action='consolidation_apply_run',
            tool_name='get_memory_consolidation_apply_run',
            purpose='Szczegoly jednego consolidation_apply_run w trybie read-only.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int'},
        ),
        WorkshopAction(
            action='consolidation_lifecycle_report',
            tool_name='get_memory_consolidation_lifecycle_report',
            purpose='Raport read-only laczacy proposal, review, apply, rollback i snapshot/integrity status.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null',
 'proposal_id': 'str|null',
 'proposal_status': 'str|null',
 'include_completed': 'bool',
 'include_rejected': 'bool',
 'include_apply_runs': 'bool',
 'include_rollback_details': 'bool',
 'include_snapshot_integrity': 'bool',
 'limit': 'int'},
        ),
        WorkshopAction(
            action='consolidation_apply_rollback_preview',
            tool_name='preview_memory_consolidation_apply_rollback',
            purpose='Read-only preview rollbacku dla consolidation_apply_run; zwraca wymagany rollback_preview_hash do execute.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int'},
        ),
        WorkshopAction(
            action='consolidation_apply_rollback',
            tool_name='rollback_memory_consolidation_apply_run',
            purpose='Wykonaj guarded rollback dla consolidation_apply_run; expected_rollback_preview_hash z preview jest wymagany.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'run_id': 'int', 'notes': 'str|null', 'expected_rollback_preview_hash': 'str'},
        ),
        WorkshopAction(
            action='consolidation_snapshot_integrity',
            tool_name='get_memory_consolidation_snapshot_integrity_report',
            purpose='Raport read-only integralnosci preview snapshots dla consolidation apply i rollback runs.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='supersession_preview',
            tool_name='preview_memory_supersession',
            purpose='Read-only preview guarded supersession dla Memory v3 lineage contracts.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'new_memory_id': 'int', 'old_memory_id': 'int', 'relation_kind': 'str', 'reason': 'str|null', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='supersession_apply',
            tool_name='apply_memory_supersession',
            purpose='Wykonaj guarded supersession apply dla Memory v3; expected_preview_hash z preview jest wymagany.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'new_memory_id': 'int',
 'old_memory_id': 'int',
 'relation_kind': 'str',
 'reason': 'str',
 'expected_preview_hash': 'str',
 'applied_by': 'str|null',
 'notes': 'str|null',
 'confirm_protected': 'bool',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='supersession_runs',
            tool_name='list_memory_supersession_runs',
            purpose='Lista read-only wykonanych supersession apply runs dla Memory v3.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str|null',
 'new_memory_id': 'int|null',
 'old_memory_id': 'int|null',
 'status': 'str|null',
 'limit': 'int'},
        ),
        WorkshopAction(
            action='supersession_run',
            tool_name='get_memory_supersession_run',
            purpose='Szczegoly jednego supersession apply run w trybie read-only.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='supersession_rollback_preview',
            tool_name='preview_memory_supersession_rollback',
            purpose='Read-only preview rollbacku dla supersession apply run; zwraca wymagany rollback_preview_hash do execute.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'run_id': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='supersession_rollback',
            tool_name='rollback_memory_supersession_run',
            purpose='Wykonaj guarded rollback dla supersession apply run; expected_rollback_preview_hash z preview jest wymagany.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'run_id': 'int',
 'expected_rollback_preview_hash': 'str',
 'rolled_back_by': 'str|null',
 'notes': 'str|null',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='explain_retrieval',
            tool_name='explain_retrieval',
            purpose='Wyjasnij jak retrieval rozwiazal query i dlaczego zwrocil takie wyniki.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'query': 'str',
 'project_key': 'str|null',
 'project_key_mode': 'str',
 'limit': 'int',
 'include_candidates': 'bool',
 'include_rejected': 'bool',
 'include_recent_probe': 'bool'},
        ),
        WorkshopAction(
            action='search_qa_report',
            tool_name='search_qa_report',
            purpose='Uruchom deterministyczny smoke QA dla retrieval i recent search.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_keys': 'array|null', 'limit_per_case': 'int'},
        ),
        WorkshopAction(
            action='capture_proposal',
            tool_name='propose_memory_capture',
            purpose='Przygotuj propozycje zapisu memory bez zapisu do bazy.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'content': 'str',
 'project_key': 'str|null',
 'source_context': 'str|null',
 'conversation_key': 'str|null',
 'hint': 'str|null'},
        ),
        WorkshopAction(
            action='capture_save',
            tool_name='save_memory_capture_proposal',
            purpose='Zapisz durable capture review item bez tworzenia memory.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'content': 'str',
 'project_key': 'str|null',
 'scope_code': 'str|null',
 'source_context': 'str|null',
 'conversation_key': 'str|null',
 'source_event_ref': 'str|null',
 'hint': 'str|null',
 'expires_at': 'str|null'},
        ),
        WorkshopAction(
            action='capture_list',
            tool_name='list_memory_capture_review_items',
            purpose='Lista durable capture review items.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'status': 'str|null',
 'project_key': 'str|null',
 'scope_code': 'str|null',
 'created_after': 'str|null',
 'created_before': 'str|null',
 'limit': 'int',
 'include_expired': 'bool'},
        ),
        WorkshopAction(
            action='capture_get',
            tool_name='get_memory_capture_review_item',
            purpose='Pobierz jeden durable capture review item.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'item_id': 'int'},
        ),
        WorkshopAction(
            action='capture_review_decide',
            tool_name='review_memory_capture_item',
            purpose='Approve albo reject durable capture review item bez tworzenia memory.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'item_id': 'int', 'decision': 'str', 'reviewed_by': 'str|null', 'review_note': 'str|null'},
        ),
        WorkshopAction(
            action='capture_expire',
            tool_name='expire_memory_capture_item',
            purpose='Oznacz durable capture review item jako expired bez tworzenia memory.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'item_id': 'int', 'reason': 'str', 'expired_by': 'str|null'},
        ),
        WorkshopAction(
            action='capture_reconciliation_preview',
            tool_name='preview_memory_capture_reconciliation',
            purpose='Deterministyczny preview reconciliation dla capture review item; tylko shortlist/evidence, bez apply.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'item_id': 'int',
 'candidate_limit': 'int',
 'semantic_limit': 'int',
 'include_semantic': 'bool',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='capture_apply',
            tool_name='apply_memory_capture_reconciliation',
            purpose='Atomowo wykonaj zatwierdzony i świeży Memory v3 reconciliation preview.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'item_id': 'int',
 'expected_preview_hash': 'str',
 'applied_by': 'str',
 'notes': 'str|null',
 'confirm_protected': 'bool',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='retention_preview',
            tool_name='preview_memory_retention_policy',
            purpose='Read-only redacted sensitivity and retention preview.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'memory_id': 'int', 'as_of': 'str|null', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='retention_project_preview',
            tool_name='preview_project_memory_retention',
            purpose='Read-only redacted project retention preview.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'as_of': 'str|null', 'limit': 'int', 'include_retain': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='retention_review_save',
            tool_name='save_memory_retention_review',
            purpose='Save a durable pending retention review item.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'memory_id': 'int', 'expected_preview_hash': 'str', 'as_of': 'str|null'},
        ),
        WorkshopAction(
            action='retention_review_list',
            tool_name='list_memory_retention_reviews',
            purpose='List durable retention review items.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'status': 'str|null', 'project_key': 'str|null', 'memory_id': 'int|null', 'limit': 'int'},
        ),
        WorkshopAction(
            action='retention_review_get',
            tool_name='get_memory_retention_review',
            purpose='Get one durable retention review item.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'review_item_id': 'int'},
        ),
        WorkshopAction(
            action='retention_review_decide',
            tool_name='decide_memory_retention_review',
            purpose='Approve or reject a retention review item.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'review_item_id': 'int', 'decision': 'str', 'reviewed_by': 'str', 'review_note': 'str|null'},
        ),
        WorkshopAction(
            action='retention_apply',
            tool_name='apply_memory_retention_review',
            purpose='Apply one approved fresh retention review item.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'review_item_id': 'int',
 'expected_preview_hash': 'str',
 'applied_by': 'str',
 'notes': 'str|null',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='retention_apply_batch',
            tool_name='apply_memory_retention_batch',
            purpose='Apply 1..10 retention items atomically after a trusted internal online backup.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'review_item_ids_json': 'str', 'expected_preview_hashes_json': 'str', 'applied_by': 'str', 'notes': 'str|null'},
        ),
        WorkshopAction(
            action='retention_rollback_preview',
            tool_name='preview_memory_retention_rollback',
            purpose='Preview exact rollback for archive or expire.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'review_item_id': 'int'},
        ),
        WorkshopAction(
            action='retention_rollback',
            tool_name='rollback_memory_retention_review',
            purpose='Rollback an applied archive or expire action.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'review_item_id': 'int', 'expected_rollback_preview_hash': 'str', 'rolled_back_by': 'str', 'notes': 'str|null'},
        ),
        WorkshopAction(
            action='create_from_proposal',
            tool_name='create_memory_from_proposal',
            purpose='Zatwierdz propozycje zapisu i utworz memory.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'proposal_json': 'str',
 'content': 'str|null',
 'summary_short': 'str|null',
 'title': 'str|null',
 'project_key': 'str|null',
 'tags': 'str|null',
 'source_context': 'str|null'},
        ),
        WorkshopAction(
            action='project_brief',
            tool_name='get_project_brief',
            purpose='Zbuduj kompaktowy brief projektu po resolved project_key.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str',
 'limit': 'int',
 'include_recent': 'bool',
 'include_next_steps': 'bool',
 'include_risks': 'bool',
 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='project_card',
            tool_name='get_project_card',
            purpose='Zbuduj zywa karte projektu po resolved project_key.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'limit': 'int', 'include_recent': 'bool', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='recent_project_changes',
            tool_name='get_recent_project_changes',
            purpose='Pobierz ostatnie zmiany projektu chronologicznie.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'project_key': 'str', 'since_id': 'int|null', 'since_date': 'str|null', 'limit': 'int', 'include_debug': 'bool'},
        ),
        WorkshopAction(
            action='provenance_backfill_preview',
            tool_name='preview_memory_provenance_backfill',
            purpose='Preview evidence-bound repair of legacy provenance gaps without mutation.',
            min_profile='clean_operator',
            risk='low',
            risk_class='R0',
            backup_required=False,
            payload_schema={'project_key': 'str|null', 'sample_limit': 'int'},
        ),
        WorkshopAction(
            action='provenance_backfill_apply',
            tool_name='apply_memory_provenance_backfill',
            purpose='Apply a fresh provenance backfill preview after a trusted SQLite backup.',
            min_profile='admin',
            risk='high',
            risk_class='R3',
            backup_required=True,
            payload_schema={
                'expected_preview_hash': 'str',
                'project_key': 'str|null',
                'applied_by': 'str',
                'confirm_provenance_repair': 'bool',
            },
        ),
        WorkshopAction(
            action='get',
            tool_name='get_memory',
            purpose='Pobierz konkretne memory po ID.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'memory_id': 'int'},
        ),
        WorkshopAction(
            action='links',
            tool_name='get_memory_links',
            purpose='Pobierz graf linkĂłw dla memory.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'memory_id': 'int'},
        ),
        WorkshopAction(
            action='save',
            tool_name='save_memory',
            purpose='Bezpośrednio zapisz jawne lub świadomie autonomiczne wspomnienie Jagody.',
            min_profile='agent',
            risk='medium',
            payload_schema={
                'content': 'str', 'memory_type': 'str', 'summary_short': 'str|null',
                'project_key': 'str|null', 'scope_code': 'str|null', 'tags': 'str|null',
                'title': 'str|null', 'entry_type': 'str|null', 'truth_kind': 'str|null',
                'source_context': 'str|null', 'conversation_key': 'str|null',
                'source_event_ref': 'str|null', 'importance_score': 'float',
                'confidence_score': 'float', 'write_intent': 'str',
                'supersedes_memory_id': 'int|null', 'supersession_relation': 'str|null',
                'supersession_scope': 'str|null',
            },
        ),
        WorkshopAction(
            action='propose',
            tool_name='propose_memory',
            purpose='Wyślij niepewną lub agentową propozycję do capture queue.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={
                'content': 'str', 'project_key': 'str|null', 'scope_code': 'str|null',
                'source_context': 'str|null', 'conversation_key': 'str|null',
                'source_event_ref': 'str|null', 'hint': 'str|null', 'expires_at': 'str|null',
            },
        ),
        WorkshopAction(
            action='create',
            tool_name='create_memory',
            purpose='Legacy compatibility alias; może kierować zapis do capture reconciliation.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'content': 'str', 'memory_type': 'str', 'project_key': 'str|null', 'tags': 'str|null'},
        ),
        WorkshopAction(
            action='admin_write',
            tool_name='admin_memory_write',
            purpose='Ciężki audytowany zapis naprawczy lub migracyjny operatora.',
            min_profile='admin',
            risk='high',
            payload_schema={'payload': 'object', 'operator_id': 'str', 'reason': 'str', 'source_event_ref': 'str'},
        ),
        WorkshopAction(
            action='create_direct_confirmed',
            tool_name='create_memory_direct_confirmed',
            purpose='Legacy admin-only alias dla audytowanego direct write.',
            min_profile='admin',
            risk='high',
            payload_schema={'payload': 'object', 'operator_id': 'str', 'reason': 'str', 'source_event_ref': 'str'},
        ),
        WorkshopAction(
            action='recall',
            tool_name='recall_memory',
            purpose='Lekki recall z pamiÄ™ci.',
            min_profile='clean_operator',
            risk='low',
            risk_class='R1',
            payload_schema={
                'memory_id': 'int',
                'strength': 'float',
                'recall_type': 'str',
                'source': 'str|null',
            },
        ),
        WorkshopAction(
            action='recall_telemetry',
            tool_name='get_memory_recall_telemetry',
            purpose='Read append-only recall telemetry without changing durable importance.',
            min_profile='clean_operator',
            risk='low',
            risk_class='R0',
            payload_schema={
                'memory_id': 'int',
                'limit': 'int',
                'recall_type': 'str|null',
            },
        ),
        WorkshopAction(
            action='project_aliases',
            tool_name='list_project_key_aliases',
            purpose='Lista aliasĂłw project_key.',
            min_profile='clean_operator',
            risk='low',
            payload_schema={'canonical_project_key': 'str|null', 'include_inactive': 'bool'},
        ),
        WorkshopAction(
            action='upsert_project_alias',
            tool_name='upsert_project_key_alias',
            purpose='Dodaj lub zaktualizuj alias project_key.',
            min_profile='clean_operator',
            risk='medium',
            payload_schema={'canonical_project_key': 'str',
 'alias_project_key': 'str',
 'alias_kind': 'str|null',
 'status': 'str|null',
 'notes': 'str|null'},
        ),
    ),
    guardrails=(),
)
