from __future__ import annotations

"""Owner workload tool orchestration payloads."""

from typing import Any, Callable


def operational_queue_dashboard_tool_payload(
    conn: Any,
    *,
    limit_per_queue: int = 5,
    validated_before: str | None = None,
    as_of: str | None = None,
    scope_code: str | None = None,
    project_key: str | None = None,
    layer_code: str | None = None,
    area_code: str | None = None,
    memory_type: str | None = None,
    tag: str | None = None,
    text_query: str | None = None,
    effective_owner_key: str | None = None,
    effective_owner_type: str | None = None,
    cross_project_flag_key: str,
    list_review_queue: Callable[..., dict[str, Any]],
    list_revalidation_queue: Callable[..., dict[str, Any]],
    list_expired_memories: Callable[..., dict[str, Any]],
    list_duplicate_candidates_admin: Callable[..., dict[str, Any]],
    list_overdue_review_queue: Callable[..., dict[str, Any]],
    list_overdue_revalidation_queue: Callable[..., dict[str, Any]],
    list_overdue_expired_queue: Callable[..., dict[str, Any]],
    list_overdue_duplicate_queue: Callable[..., dict[str, Any]],
    get_owner_catalog_repair_summary: Callable[..., dict[str, Any]],
    operational_queue_dashboard_payload: Callable[..., dict[str, Any]],
    get_feature_flag_config: Callable[..., dict[str, Any]],
    evaluate_feature_flag_config: Callable[..., dict[str, Any]],
    normalize_optional_text: Callable[[Any], str | None],
    normalize_scope_code: Callable[[Any], str | None],
    normalize_layer_code: Callable[[Any], str | None],
    normalize_area_code: Callable[[Any], str | None],
) -> dict[str, Any]:
    review_queue = list_review_queue(
        limit=limit_per_queue,
        memory_type=memory_type,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    revalidation_queue = list_revalidation_queue(
        limit=limit_per_queue,
        validated_before=validated_before,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    expired_queue = list_expired_memories(
        limit=limit_per_queue,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    duplicate_queue = list_duplicate_candidates_admin(
        limit=limit_per_queue,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    overdue_review_queue = list_overdue_review_queue(limit=limit_per_queue, as_of=as_of, scope_code=scope_code, project_key=project_key)
    overdue_revalidation_queue = list_overdue_revalidation_queue(limit=limit_per_queue, as_of=as_of, scope_code=scope_code, project_key=project_key)
    overdue_expired_queue = list_overdue_expired_queue(limit=limit_per_queue, as_of=as_of, scope_code=scope_code, project_key=project_key)
    overdue_duplicate_queue = list_overdue_duplicate_queue(limit=limit_per_queue, as_of=as_of, scope_code=scope_code, project_key=project_key)

    normalized_scope = normalize_scope_code(scope_code)
    normalized_project_key = normalize_optional_text(project_key)
    owner_catalog_repair_summary = get_owner_catalog_repair_summary(
        project_key=normalized_project_key,
        scope_code=normalized_scope,
        limit_recent_audits=max(5, int(limit_per_queue)),
        max_groups=max(5, int(limit_per_queue)),
    )

    return operational_queue_dashboard_payload(
        conn,
        limit_per_queue=limit_per_queue,
        validated_before=validated_before,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
        review_queue=review_queue,
        revalidation_queue=revalidation_queue,
        expired_queue=expired_queue,
        duplicate_queue=duplicate_queue,
        overdue_review_queue=overdue_review_queue,
        overdue_revalidation_queue=overdue_revalidation_queue,
        overdue_expired_queue=overdue_expired_queue,
        overdue_duplicate_queue=overdue_duplicate_queue,
        owner_catalog_repair_summary=owner_catalog_repair_summary,
        feature_flag_key=cross_project_flag_key,
        get_feature_flag_config=get_feature_flag_config,
        evaluate_feature_flag_config=evaluate_feature_flag_config,
        normalize_optional_text=normalize_optional_text,
        normalize_scope_code=normalize_scope_code,
        normalize_layer_code=normalize_layer_code,
        normalize_area_code=normalize_area_code,
    )


def effective_owner_workload_tool_payload(
    *,
    limit: int = 50,
    validated_before: str | None = None,
    as_of: str | None = None,
    scope_code: str | None = None,
    project_key: str | None = None,
    layer_code: str | None = None,
    area_code: str | None = None,
    memory_type: str | None = None,
    tag: str | None = None,
    text_query: str | None = None,
    effective_owner_key: str | None = None,
    effective_owner_type: str | None = None,
    list_review_queue: Callable[..., dict[str, Any]],
    list_revalidation_queue: Callable[..., dict[str, Any]],
    list_expired_memories: Callable[..., dict[str, Any]],
    list_duplicate_candidates_admin: Callable[..., dict[str, Any]],
    list_overdue_review_queue: Callable[..., dict[str, Any]],
    list_overdue_revalidation_queue: Callable[..., dict[str, Any]],
    list_overdue_expired_queue: Callable[..., dict[str, Any]],
    list_overdue_duplicate_queue: Callable[..., dict[str, Any]],
    effective_owner_workload_payload: Callable[..., dict[str, Any]],
    normalize_optional_text: Callable[[Any], str | None],
    normalize_scope_code: Callable[[Any], str | None],
    normalize_layer_code: Callable[[Any], str | None],
    normalize_area_code: Callable[[Any], str | None],
) -> dict[str, Any]:
    review_queue = list_review_queue(
        limit=1000,
        memory_type=memory_type,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    revalidation_queue = list_revalidation_queue(
        limit=1000,
        validated_before=validated_before,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    expired_queue = list_expired_memories(
        limit=1000,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    duplicate_queue = list_duplicate_candidates_admin(
        limit=1000,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    overdue_review_queue = list_overdue_review_queue(
        limit=1000,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    overdue_revalidation_queue = list_overdue_revalidation_queue(
        limit=1000,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    overdue_expired_queue = list_overdue_expired_queue(
        limit=1000,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )
    overdue_duplicate_queue = list_overdue_duplicate_queue(
        limit=1000,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
    )

    return effective_owner_workload_payload(
        limit=limit,
        validated_before=validated_before,
        as_of=as_of,
        scope_code=scope_code,
        project_key=project_key,
        layer_code=layer_code,
        area_code=area_code,
        memory_type=memory_type,
        tag=tag,
        text_query=text_query,
        effective_owner_key=effective_owner_key,
        effective_owner_type=effective_owner_type,
        review_queue=review_queue,
        revalidation_queue=revalidation_queue,
        expired_queue=expired_queue,
        duplicate_queue=duplicate_queue,
        overdue_review_queue=overdue_review_queue,
        overdue_revalidation_queue=overdue_revalidation_queue,
        overdue_expired_queue=overdue_expired_queue,
        overdue_duplicate_queue=overdue_duplicate_queue,
        normalize_optional_text=normalize_optional_text,
        normalize_scope_code=normalize_scope_code,
        normalize_layer_code=normalize_layer_code,
        normalize_area_code=normalize_area_code,
    )
