from __future__ import annotations

from app.workshops.contracts import Workshop, WorkshopAction

WORKSHOP = Workshop(
    area='admin',
    purpose='Pliki, SQL, migracje i narzÄ™dzia operatorskie.',
    min_profile='clean_operator',
    risk='high',
    recommended_first_action='db_info',
    actions=(
        WorkshopAction(
            action='db_info',
            tool_name='get_db_info',
            purpose='Informacje o bazie.',
            min_profile='admin',
            risk='medium',
            payload_schema=None,
        ),
        WorkshopAction(
            action='query_sql',
            tool_name='query_sql',
            purpose='Wykonaj SQL.',
            min_profile='admin',
            risk='high',
            payload_schema={'query': 'str', 'params_json': 'str|null', 'max_rows': 'int', 'allow_write': 'bool'},
        ),
        WorkshopAction(
            action='read_file',
            tool_name='read_file_text',
            purpose='Odczytaj plik.',
            min_profile='admin',
            risk='medium',
            payload_schema={'path': 'str'},
        ),
        WorkshopAction(
            action='write_file',
            tool_name='write_file_text',
            purpose='Zapisz plik.',
            min_profile='admin',
            risk='high',
            payload_schema={'path': 'str', 'content': 'str'},
        ),
        WorkshopAction(
            action='insert_before_marker',
            tool_name='insert_before_marker',
            purpose='Wstaw tekst przed dokĹ‚adnym markerem w pliku.',
            min_profile='admin',
            risk='high',
            payload_schema={'path': 'str',
 'marker': 'str',
 'content': 'str',
 'encoding': 'str',
 'dry_run': 'bool',
 'backup': 'bool',
 'require_marker_once': 'bool'},
        ),
        WorkshopAction(
            action='insert_after_marker',
            tool_name='insert_after_marker',
            purpose='Wstaw tekst po dokĹ‚adnym markerze w pliku.',
            min_profile='admin',
            risk='high',
            payload_schema={'path': 'str',
 'marker': 'str',
 'content': 'str',
 'encoding': 'str',
 'dry_run': 'bool',
 'backup': 'bool',
 'require_marker_once': 'bool'},
        ),
        WorkshopAction(
            action='replace_once',
            tool_name='replace_once',
            purpose='ZamieĹ„ dokĹ‚adnie jedno wystÄ…pienie tekstu w pliku.',
            min_profile='admin',
            risk='high',
            payload_schema={'path': 'str', 'find': 'str', 'replace': 'str', 'encoding': 'str', 'dry_run': 'bool', 'backup': 'bool'},
        ),
        WorkshopAction(
            action='delete_path',
            tool_name='delete_path',
            purpose='UsuĹ„ Ĺ›cieĹĽkÄ™.',
            min_profile='admin',
            risk='high',
            payload_schema={'path': 'str'},
        ),
        WorkshopAction(
            action='run_shell',
            tool_name='run_shell',
            purpose='Run the platform-native administrative shell.',
            min_profile='admin',
            risk='high',
            payload_schema={'script': 'str', 'workdir': 'str|null', 'timeout_seconds': 'int'},
        ),
        WorkshopAction(
            action='run_powershell',
            tool_name='run_powershell',
            purpose='Run PowerShell on Windows (compatibility alias).',
            min_profile='admin',
            risk='high',
            payload_schema={'script': 'str', 'workdir': 'str|null', 'timeout_seconds': 'int'},
        ),
        WorkshopAction(
            action='run_pytest',
            tool_name='run_pytest',
            purpose='Uruchom pytest.',
            min_profile='admin',
            risk='medium',
            payload_schema={'test_path': 'str|null', 'timeout_seconds': 'int'},
        ),
        WorkshopAction(
            action='git_status',
            tool_name='git_status',
            purpose='PokaĹĽ git status --short.',
            min_profile='admin',
            risk='medium',
            payload_schema={'workdir': 'str|null'},
        ),
        WorkshopAction(
            action='git_commit',
            tool_name='git_commit',
            purpose='StwĂłrz commit git.',
            min_profile='admin',
            risk='high',
            payload_schema={'message': 'str', 'workdir': 'str|null', 'stage_all': 'bool'},
        ),
        WorkshopAction(
            action='git_push',
            tool_name='git_push',
            purpose='Wypchnij branch git.',
            min_profile='admin',
            risk='high',
            payload_schema={'remote': 'str', 'branch': 'str|null', 'workdir': 'str|null'},
        ),
    ),
    guardrails=(),
)
